#!/bin/bash

#install helm
curl -kL https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz -o /usr/local/bin/helm.tar.gz
tar -xvf /usr/local/bin/helm.tar.gz -C /usr/local/bin
mv /usr/local/bin/linux-amd64/helm /usr/local/bin/helm
rm -rf /usr/local/bin/linux-amd64
chmod +x /usr/local/bin/helm

# create a new project namespace for Backstage
oc new-project backstage

# Add helm repos:
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add backstage https://backstage.github.io/charts

# Update values-openshift.yaml
export APP_HOST_SUBDOMAIN="$HOSTNAME.crc.$INSTRUQT_PARTICIPANT_ID.instruqt.io"
cat <<EOF > /tmp/values-openshift.yaml
backstage:
  image:
    registry: ghcr.io
    repository: janus-idp/redhat-backstage-build
    tag: latest
  extraEnvVars:
    - name: "APP_CONFIG_app_baseUrl"
      value: "https://{{ .Values.ingress.host }}"
    - name: "APP_CONFIG_backend_baseUrl"
      value: "https://{{ .Values.ingress.host }}"
    - name: "APP_CONFIG_backend_cors_origin"
      value: "https://{{ .Values.ingress.host }}"
    - name: "APP_CONFIG_backend_database_client"
      value: pg
    - name: "APP_CONFIG_backend_database_connection_host"
      value: "{{ include \"backstage.postgresql.host\" . }}"
    - name: "APP_CONFIG_backend_database_connection_port"
      value: '5432'
    - name: "APP_CONFIG_backend_database_connection_user"
      value: "{{ .Values.postgresql.auth.username }}"
    - name: "APP_CONFIG_backend_database_connection_password"
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: "{{ include \"backstage.postgresql.fullname\" . }}"
  installDir: /opt/app-root/src
 
ingress:
  enabled: true
  host: backstage.apps.${APP_HOST_SUBDOMAIN}
  annotations:
    route.openshift.io/termination: "edge"
 
postgresql:
  enabled: true
  database: backstage
  postgresqlDataDir: /var/lib/pgsql/data/userdata
  auth:
    username: postgres
    database: backstage
  image:
    registry: registry.redhat.io
    repository: rhel9/postgresql-13
    tag: 1-73
  primary:
    securityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true
      mountPath: /var/lib/pgsql/data
    extraEnvVars:
    - name: POSTGRESQL_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: backstage-postgresql
EOF

# Install backstage via helm chart:
helm install backstage backstage/backstage -f /tmp/values-openshift.yaml
