#!/bin/bash


dnf install -y procps-ng iputils bind-utils ansible python-pip

crc=`nslookup crc |  awk -F': ' 'NR==6 { print $2 } '`

echo "$crc api.crc.testing" >> /etc/hosts


curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.0/openshift-client-linux-4.9.0.tar.gz -o /tmp/openshift-client-linux-4.9.0.tar.gz
tar -xvf /tmp/openshift-client-linux-4.9.0.tar.gz -C /usr/bin/
chmod +x /usr/bin/oc
chmod +x /usr/bin/kubectl

pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --upgrade pip
pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --ignore-installed ipaddress openshift

mkdir -p /root/tutorial
cd /root/tutorial
ansible-galaxy init example-role --offline >> /dev/null

curl -s https://raw.githubusercontent.com/openshift-labs/learn-katacoda/master/ansibleop/ansible-k8s-modules/assets/myhosts -o /root/tutorial/myhosts
curl -s https://raw.githubusercontent.com/openshift-labs/learn-katacoda/master/ansibleop/ansible-k8s-modules/assets/nginx-deployment.yml -o /root/tutorial/nginx-deployment.yml
curl -s https://raw.githubusercontent.com/openshift-labs/learn-katacoda/master/ansibleop/ansible-k8s-modules/assets/playbook.yml -o /root/tutorial/playbook.yml


