#!/bin/bash

output=$(./hello)

search_string="Hello, Red Hat Developers Program World!"

if echo "$output" | grep -q "$search_string"; then
  FAIL "Host is not registered using subscription-manager. Please redo the steps for registration."
  exit -1
else
  exit 0
fi
