#!/bin/bash
set -x

# setup vars
export HOME=/root
export TERM=xterm-color
export KUBECONFIG=/opt/kubeconfig
echo "export TERM=xterm-color" >> /root/.bashrc
echo "export KUBECONFIG=/opt/kubeconfig" >> /root/.bashrc
echo "export HOME=/root" > /tmp/.bashrc
cat /root/.bashrc >> /tmp/.bashrc
mv /tmp/.bashrc /root/.bashrc

# set hostname
#INSTRUQT_HOSTNAME=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/hostname)

eval $(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/startup-script | grep INSTRUQT_PARTICIPANT_ID)

# start openshift
systemctl start ovs-configuration.service
BREXIP=$(ip -4 -o addr show br-ex  | awk '{print $4}' | cut -d "/" -f 1)

cat << EOF > /etc/resolv.conf
search c.rhd-devx-instruqt.internal google.internal
nameserver $BREXIP
nameserver 169.254.169.254
EOF

systemctl reload NetworkManager

cat << EOF > /etc/dnsmasq.d/crc-dnsmasq.conf
listen-address=$BREXIP
expand-hosts
log-queries
local=/crc.testing/
domain=crc.testing
address=/apps-crc.testing/$BREXIP
address=/api.crc.testing/$BREXIP
address=/api-int.crc.testing/$BREXIP
address=/crc.crc.testing/192.168.126.11
EOF

systemctl start dnsmasq.service

echo $(date)
echo "### Boostrap END ###"
