version: "3"
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-18-1
  machine_type: n1-highmem-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
