#!/bin/bash

export KN_VERSION=1.6.1

curl -kL https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 -o /root/hey
mv /root/hey /usr/local/bin/
chmod +x /usr/local/bin/hey

curl -kL https:/mirror.openshift.com/pub/openshift-v4/x86_64/clients/serverless/${KN_VERSION}/kn-linux-amd64.tar.gz -o /usr/local/bin/kn.tar.gz
tar -xvzf /usr/local/bin/kn.tar.gz -C /usr/local/bin
mv /usr/local/bin/kn-linux-amd64 /usr/local/bin/kn
chmod +x /usr/local/bin/kn

mkdir -p /root/02-serving

curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/02-serving/service.yaml -o /root/02-serving/service.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/02-serving/watch-service.bash -o /root/02-serving/watch-service.bash

mkdir -p /root/03-traffic-distribution

curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/03-traffic-distribution/greeter-v1-service.yaml -o /root/03-traffic-distribution/greeter-v1-service.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/03-traffic-distribution/greeter-v2-service.yaml -o /root/03-traffic-distribution/greeter-v2-service.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/03-traffic-distribution/service-pinned.yaml -o /root/03-traffic-distribution/service-pinned.yaml

mkdir -p /root/04-canary-releases

curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/04-canary-releases/greeter-canary-service.yaml -o /root/04-canary-releases/greeter-canary-service.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/04-canary-releases/poll-svc-10.bash -o /root/04-canary-releases/poll-svc-10.bash

mkdir -p /root/05-scaling

curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/05-scaling/service-50.yaml -o /root/05-scaling/service-50.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/05-scaling/service-hpa.yaml -o /root/05-scaling/service-hpa.yaml
curl -s https:/raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/05-scaling/service-min-max-scale.yaml -o /root/05-scaling/service-min-max-scale.yaml

# Setting up Serverless
curl https://raw.githubusercontent.com/openshift-instruqt/instruqt/master/instruqt-tracks/developing-on-openshift-serverless/scripts/01-prepare/install-serverless.bash | bash
