#!/bin/bash
check_moon_buggy_exist=$(podman image list | grep "moon-buggy" | wc | awk '{print $1}')

if [[ $check_moon_buggy_exist -eq 1 ]];then
    echo "Congratualtions You can successfully move towards the next step"
else
    fail-message "Please create an image as 'moon-buggy' for the lab to proceed"
fi