#!/bin/bash
podman stop --all
podman rm --all
mkdir php-webpage && cd php-webpage

cat > index.php << EOF
<html>
<body>
<?php print "Hello, world!\n" ?>
</body>
</html>
EOF

cat > Containerfile << EOF
FROM registry.access.redhat.com/ubi9/ubi

RUN yum --disableplugin=subscription-manager -y module enable \
  php:8.1 \
  && yum --disableplugin=subscription-manager -y install \
  httpd php \
  && yum --disableplugin=subscription-manager clean all

ADD index.php /var/www/html

RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /run/php-fpm \
  && chmod -R g=u /var/log/httpd /var/run/httpd /run/php-fpm

EXPOSE 8080

USER 1001

CMD php-fpm & httpd -D FOREGROUND
EOF

sudo podman build -t php-ubi .
sudo podman run --name hello -p 8080:8080 -d localhost/php-ubi
podman ps
curl localhost:8080