#!/bin/bash
set -euxo pipefail

echo "Authenticating login credentials using 'oc login'"

oc login -u admin -p admin

echo "Creating new project 'myproject': oc new-project myproject"
oc new-project myproject
