#!/bin/bash


dnf install -y procps-ng iputils tree bind-utils make automake gcc gcc-c++

crc=`nslookup crc |  awk -F': ' 'NR==6 { print $2 } '`

echo "$crc api.crc.testing" >> /etc/hosts

export OPENSHIFT_RELEASE_VERSION="4.11.7"

curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OPENSHIFT_RELEASE_VERSION/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -o /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz
tar -xvf /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -C /usr/bin/
chmod +x /usr/bin/oc
chmod +x /usr/bin/kubectl

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/scripts/install_operatorsdk_toolbox.sh -o /tmp/install.sh && bash /tmp/install.sh

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/operatorframework/go-operator-memcached/assets/memcached_types.go -o /tmp/memcached_types.go
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/operatorframework/go-operator-memcached/assets/memcached_controller.go -o /tmp/memcached_controller.go
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/operatorframework/go-operator-memcached/assets/cache_v1alpha1_memcached.yaml -o /tmp/cache_v1alpha1_memcached.yaml

mkdir -p /root/projects/memcached-operator

cd /root/projects/memcached-operator

operator-sdk init --domain example.com --repo github.com/example/memcached-operator

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done




