#!/bin/bash

curl https://raw.githubusercontent.com/openshift-instruqt/instruqt/master/scripts/install_java.sh | bash

export JAVA_HOME=/opt/java/jdk-11/
export MAVEN_HOME=/opt/java/apache-maven-3.8.5/
export PATH="$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH"

mkdir -p /root/projects/quarkus
echo "-w \"\n\"" >> ~/.curlrc