#!/bin/bash

export OPENSHIFT_RELEASE_VERSION="4.10.12"

dnf install -y procps-ng iputils bind-utils git java-11-openjdk-devel.x86_64 maven

crc=`nslookup crc |  awk -F': ' 'NR==6 { print $2 } '`

echo "$crc api.crc.testing" >> /etc/hosts

curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OPENSHIFT_RELEASE_VERSION/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -o /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz
tar -xvf /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -C /usr/bin/
chmod +x /usr/bin/oc
chmod +x /usr/bin/kubectl

export ODO_INSTALL="latest"
export ODO_RESPONSE=$(odo version 2> /dev/null)
export ODO_VERSION=${ODO_RESPONSE:0:10}

curl -o odo.tar.gz -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/$ODO_INSTALL/odo-linux-amd64.tar.gz && \
tar -xvf odo.tar.gz && \
rm -f odo.tar.gz && \
mv -f odo /usr/bin/odo && \
chmod +x /usr/bin/odo && \
odo preference set -f ConsentTelemetry false > /dev/null 2>&1
odo preference set UpdateNotification false > /dev/null 2>&1

export HELM_VERSION=3.3.4
curl -o /usr/local/bin/helm https://mirror.openshift.com/pub/openshift-v4/clients/helm/$HELM_VERSION/helm-linux-amd64 && chmod a+x /usr/local/bin/helm
mkdir -p /root/my-chart
mkdir -p /root/my-chart/templates
mkdir -p /root/my-chart/templates/tests
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/Chart.yaml -o /root/my-chart/Chart.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/values.yaml -o /root/my-chart/values.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/NOTES.txt -o /root/my-chart/templates/NOTES.txt
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/_helpers.tpl -o /root/my-chart/templates/_helpers.tpl
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/deployment.yaml -o /root/my-chart/templates/deployment.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/ingress.yaml -o /root/my-chart/templates/ingress.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/service.yaml -o /root/my-chart/templates/service.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/serviceaccount.yaml -o /root/my-chart/templates/serviceaccount.yaml
curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/tests/test-connection.yaml -o /root/my-chart/templates/tests/test-connection.yaml

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done
