version: "3"
containers:
- name: container
  image: fedora
  shell: /bin/bash
virtualmachines:
- name: crc
  image: instruqt-4-10/crc-2-9-0-wkzjw
  machine_type: n1-highmem-4
  allow_external_ingress:
  - http
  - https
  - high-ports
