#!/bin/bash

dnf install -y procps-ng iputils bind-utils postgresql

crc=`nslookup crc |  awk -F': ' 'NR==6 { print $2 } '`

echo "$crc api.crc.testing" >> /etc/hosts

export OC_VERSION=4.11.7
export HELM_VERSION=3.3.4

curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OC_VERSION/openshift-client-linux-$OC_VERSION.tar.gz -o /tmp/openshift-client-linux-$OC_VERSION.tar.gz
tar -xvf /tmp/openshift-client-linux-$OC_VERSION.tar.gz -C /usr/bin/
chmod +x /usr/bin/oc
chmod +x /usr/bin/kubectl


curl -o /usr/local/bin/helm https://mirror.openshift.com/pub/openshift-v4/clients/helm/$HELM_VERSION/helm-linux-amd64 && chmod a+x /usr/local/bin/helm

mkdir -p /root/my-chart
mkdir -p /root/my-chart/templates
mkdir -p /root/my-chart/templates/tests

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/Chart.yaml -o /root/my-chart/Chart.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/values.yaml -o /root/my-chart/values.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/NOTES.txt -o /root/my-chart/templates/NOTES.txt

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/_helpers.tpl -o /root/my-chart/templates/_helpers.tpl

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/deployment.yaml -o /root/my-chart/templates/deployment.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/ingress.yaml -o /root/my-chart/templates/ingress.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/service.yaml -o /root/my-chart/templates/service.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/serviceaccount.yaml -o /root/my-chart/templates/serviceaccount.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/developing-on-openshift/helm/assets/my-chart/templates/tests/test-connection.yaml -o /root/my-chart/templates/tests/test-connection.yaml

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done




