#!/bin/bash

curl https://raw.githubusercontent.com/openshift-instruqt/instruqt/master/scripts/install_java_graalvm.sh | bash

mkdir -p /root/projects/quarkus
rm -Rf /root/projects/quarkus/getting-started
echo "-w \"\n\"" >> ~/.curlrc
