#!/bin/bash


dnf install -y procps-ng iputils bind-utils tree make automake gcc gcc-c++ ansible python-pip python-ansible-runner

crc=`nslookup crc |  awk -F': ' 'NR==6 { print $2 } '`

echo "$crc api.crc.testing" >> /etc/hosts

export OPENSHIFT_RELEASE_VERSION="4.11.7"

curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OPENSHIFT_RELEASE_VERSION/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -o /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz
tar -xvf /tmp/openshift-client-linux-$OPENSHIFT_RELEASE_VERSION.tar.gz -C /usr/bin/
chmod +x /usr/bin/oc
chmod +x /usr/bin/kubectl

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/scripts/install_operatorsdk_toolbox.sh -o /tmp/install.sh && bash /tmp/install.sh

mkdir -p /root/tutorial
mkdir -p /opt/ansible/roles

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/operatorframework/ansible-operator-overview/assets/watches.yaml -o /tmp/watches.yaml

curl -s https://raw.githubusercontent.com/openshift-instruqt/instruqt/v0.0.4/operatorframework/ansible-operator-overview/assets/cache_v1alpha1_memcached.yaml -o /tmp/cache_v1alpha1_memcached.yaml

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done
 
