#!/bin/bash

kill -9 $(ps aux | grep reactive-sql | grep -v grep | awk '{print $2}')
export APP_ROUTE=`oc get route reactive-sql -n reactive-sql -o jsonpath='{"http://"}{.spec.host}'`
echo ${APP_URL}
nohup mvn quarkus:remote-dev -Dquarkus.live-reload.url=$APP_ROUTE -f /root/projects/rhoar-getting-started/quarkus/reactive-sql > /root/log.out 2> /root/log.err < /dev/null & disown