version: "3"
virtualbrowsers:
- name: rhd-login-3882345
  url: https://developers.redhat.com/node/284339?auHash=5k9QV-yD0z-jAU7XkJyq1TUxhVyyZVLiuZz7tsfTz_s&offerid=3882345
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-14-7-97g8f
  machine_type: n1-highmem-4
  allow_external_ingress:
  - http
  - https
  - high-ports
