name: Track Dev
description: Converts track to a dev version for testing.
inputs:
  path:
    description: Path to the Instruqt track.
    required: true
runs:
  using: composite
  steps:
  - name: Create dev track
    shell: bash
    run: |
      cd ${{ inputs.path }}

      # Check whether this is already a dev version track
      ISDEV=$(yq '.slug | contains("-dev")' track.yml)
      if [[ $ISDEV == "true" ]]; then
        echo -e "It looks like the track slug already has the -dev suffix"
        exit 1
      fi
      
      # Strip out the track ids and rename the dev track
      echo "Converting track to dev version..."
      for file in $(find . -name assignment.md); do
        yq eval --inplace --front-matter=process 'del(.id)' $file
      done
      
      # Remove IDs and update slugs/titles
      yq eval --inplace 'del(.id)' track.yml
      yq eval --inplace '.slug += "-dev"' track.yml
      yq eval --inplace '.title = "DEV - " + .title' track.yml
      
      # Replace prod tag with dev tag
      yq eval --inplace 'del(.tags[] | select(. == "prod"))' track.yml
      yq eval --inplace '.tags = .tags + "dev" ' track.yml
      
      # Set into maintenance mode
      yq eval --inplace '.maintenance = true' track.yml